version: '3.9'
services:
  nestapp:
    container_name: nestapp
    image: ccc/nestapp:1.0.0
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=MOTOR_INSURANCE_WEBSITE
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=MOTOR_INSURANCE_WEBSITE
    ports:
      - "5432:5432"